theme: minima
title: Demo STAT228 data science portfolio
author: Nicole Rockweiler
description: |
  An example of a data science portfolio showcasing coursework and 
  projects from STAT228: Introduction to Data Science. Designed to 
  highlight coding skills, data analysis, and project-based learning.
